#!/usr/bin/env python3
import sys
import numpy as np
from math import *

def my_error():
    ac = len(sys.argv)
    i = 1;
    j = 0;
    if (ac != 8 and ac != 2):
        print("Invalid amount of arguments")
        return (84)
    if (sys.argv[ac - 1] != '-h' and ac == 2):
        print("Invalid amount of arguments")
        return (84)
    if (sys.argv[ac - 1] == '-h' and ac ==2):
        return (0)
#    while (i != ac):
 #       j = 0
  #      while (sys.argv[i][j] != '\0'):
   #         if (sys.argv[i][j] < '0' and sys.argv[i][j] > '9' and sys.argv[i][j] != '-'):
    #            return (84)
     #       j += 1
      #  i += 1
  #  if (sys.argv[ac - 1][0] == '-' and ac == 8):
   #     print("Invalid sign of n")
    #    return (84)

def pong():
    if (sys.argv[1] == "-h"):
        print("USAGE")
        print("    ./101pong x0 y0 z0 x1 y1 z1 n")
        print("\n" "DESCRIPTION")
        print("    x0 ball abscissa at time t - 1")
        print("    y0 ball ordinate at time t - 1")
        print("    z0 ball altitude at time t - 1")
        print("    x1 ball abscissa at time t")
        print("    y1 ball ordinate at time t")
        print("    z1 ball altitude at time t")
        print("    n time shift (greater than or equal to zero, integer)")
    else:
        x0 = float(sys.argv[1])
        y0 = float(sys.argv[2])
        z0 = float(sys.argv[3])
        x1 = float(sys.argv[4])
        y1 = float(sys.argv[5])
        z1 = float(sys.argv[6])
        n = int(sys.argv[7])
        t = (sys.argv[7])
        vx = x1 - x0
        vy = y1 - y0
        vz = z1 - z0
        
        print("The velocity vector of the ball is:")
        print("(%.2f" %vx+ ", %.2f" %vy+ ", %.2f)" %vz)
        x1 += vx * n
        y1 += vy * n
        z1 += vz * n
        print("At time t + "+ t +", ball coordinates will be:")
        print("(%.2f" %x1+ ", %.2f" %y1+ ", %.2f)" %z1)
        if (sys.argv[6][0] == '-' and vz < 0 or sys.argv[6][0] != '-' and vz > 0):
            print('The ball wont reach the paddle')
        else:
            x1 -= x0
            y1 -= y0
            z1 -= z0
            x1 = sqrt(x1 * x1 + y1 * y1 + z1 * z1)
            x0 = sqrt(z1 * z1)
            x1 = degrees(asin(x0 / x1))
            print("The incidence angle is:")
            print("%.2f" %x1 + " degrees")
        return (0)

def main():
    my_error()
    pong()
main()
